spring:
  profiles.active: dev

---
spring:
  profiles: dev

server.port: 8080

rest.server.url: localhost:8080

email.service.url: http://localhost:8083/api/v1

api.server.url : https://testapi.homebank.kz
api.server.url.rest : /hb/api/v1
api.server.url.oauth : /auth/connect/token
api.client.id : hb3
api.client.secret : 21B5F798-BE55-42BC-8AA8-0025B903DC3B

database.url : jdbc:mysql://localhost:3306/deos
database.driverClassName : com.mysql.jdbc.Driver
database.username : root
database.password : 123456

# Specify the DBMS
spring.jpa.database : MYSQL

# Show or not log for each sql query
spring.jpa.show-sql : true
hibernate.dialect : org.hibernate.dialect.MySQL5Dialect
hibernate.hbm2ddl : update
spring.jpa.properties.hibernate.connection.characterEncoding: utf-8
spring.jpa.properties.hibernate.connection.CharSet: utf-8

spring.http.encoding:
    charset: UTF-8 # Charset of HTTP requests and responses. Added to the "Content-Type" header if not set explicitly.
    enabled: true # Enable http encoding support.
    force: true # Force the encoding to the configured charset on HTTP requests and responses.

openapi.authorization: b3BlbmFwaTpKaDMzNGZyZmtkaWY=
#openapi:Jh334frfkdif

spring.jackson.date-format: yyyy-MM-dd'T'HH:mm:ss


security:
  oauth2:
    client:
      client-id: deos
      client-secret: deossecret
      scope: read,write
      auto-approve-scopes: '.*'

facebook:
  client:
    clientId: 233668646673605
    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
userInfoUri: https://graph.facebook.com/me
github:
  client:
    clientId: bd1c0a783ccdd1c9b9e4
    clientSecret: 1a9030fbca47a5b2c28e92f19050bb77824b5ad1
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

logging:
  level:
org.springframework.security: DEBUG
---